### ISSUE TITLE
Can't put it in the center

### ISSUE THREAD

**Issue by mtellesy** [react-component/pagination#77]
Please help, I'm trying to put the pagination component in the center with all the ways I know but i could not.

**Comment by paranoidjk** [comment]
let's use the [default demo](http://react-component.github.io/pagination/examples/default.html) as a example, add below style.

```css
.example {
  text-align: center;
}
.rc-pagination {
 display: inline-block;
}
```

and, usage problem please ask with google or stackoverflow, we use issue to track bug.
